### ISSUE TITLE
Project/spider configuration

### ISSUE THREAD

**Issue by dtheodor** [scrapy/scrapyd#105]
Hi,

I have an issue related to configuration: I need to be being able to configure a spider differently when running it in my development environment compared how it is configured when running it through the scrapyd environment.

For example, I need the FEED_URI, FEED_FORMAT to be different when I run a spider locally than what it is when I run the spider on scrapyd. However when I deploy a new spider version, the `settings.py` file is bundled in the egg file. I would expect configuration to reside outside of what is considered the deployment unit.

What are suggested ways to overcome this?

**Comment by Digenis** [comment]
This is a support question
and it almost falls out of the scope of scrapyd.
But it's the kind of question that should be answered by FAQ
though rather in [scrapyd-client](https://github.com/scrapy/scrapyd-client)
which recently detached from scrapy.

The answer is in setuptools.
The scrapy deploy command creates a setup.py from a template
and this template includes only the modules it can find in the scrapy project
(scrapy project as defined in `scrapy.cfg`)

One way is to put settings on the top level, next to `scrapy.cfg`
where it will ignored by the default (generated) `setup.py`

You could put then such a block in you original settings
```python
try:
    import dev_settings
    from dev_settings import *
except ImportError:
    pass
```
and a file `dev_settings.py` on the top level.

dev_settings will be available to your modules
because scrapy adds the top level directory to the import path.
However when packaging the egg for scrapyd, they will be ignored.
Only modules inside your project are packaged by the default `setup.py`.

You can also write/modify `setup.py` yourself to exclude dev_settings.
This has the advantage of more control over your excluded files,
eg, you can place `dev_settings.py` next to `settings.py`, inside the project dir
or to answer your original question,
one would probably put settings.py on the top level
and update `scrapy.cfg` (and `setup.py` if generated) to know where to find the settings.

if you succeed on the second, untried, scenario and mind sharing how you do it,
let us close this issue and come up with a doc PR to scrapyd-client.

Have fun experimenting.
