### ISSUE TITLE
pypi package problem

### ISSUE THREAD

**Issue by miracledan** [scrapy/scrapyd#115]
I encounter a problem when I use 'logs_filename' to config scrapyd.
Then I checked the code on github and found 'logs_filename' was added not so long ago.

I use pypi to install this wonderful tool, the package must be obsolescent which uploaded on 2015-6-30. 
So I hope the scrapyd pypi package could be updated soon, thanks!

**Comment by Digenis** [comment]
No release is made to pypi after `1.1`.
In readthedocs you are looking at `latest` instead of `stable`.
http://scrapyd.readthedocs.org/en/stable/
Latest is taken directly from github as I see,
but stable is `1.0` , not `1.1`.

scrapyd's lack of a release-policy in the doc causes the above confusion.
See [scrapy's](http://scrapy.readthedocs.org/en/latest/versioning.html)

All features should go in `1.1`
which will be bumped to `1.2` after enough testing.
Bugfixes can be backported to branches branching off from the previous release.
@jayzeng, a `1.0` branch at 191353e1e36322712b790c09bfb906b8bb0cf504 should exist for the backported bugfixes.

**Comment by miracledan** [comment]
ok, I see it.
Thanks for your reply!
