### ISSUE TITLE
Scrapyd or scrapy

### ISSUE THREAD

**Issue by liusangel** [scrapy/scrapyd#141]
Hi, i wonder what of these two are better for my implementation. In my program the code of the spiders are in constant change, so, if I want to use scrapyd I have to add a whole new version per one tiny modification in one spider(I have like 500 spiders). In the other hand I like the Json API to interact with scrapy.  So the questions are: Is there a way to execute the modified spider code in scrapyd without add a new version? Or what happend if I add a new version while there are others spiders running? Is there a way to update just one spider change? What considerations should I have if with every change in any spider I create a new version of the project?
By the way the app is running on Laravel.

**Comment by Digenis** [comment]
This is probably a discussion for the mailing list
but I'll let it open because the problem intrigues me.

There is a setting in scrapy for a list of spider module paths.
Maybe you can point a path to a plain directory with .py files.

I'm sure this can't be easily solved with the current architecture
that just eggifies and uploads.

Maybe you can write a custom schedule.json webservice
I can't imagine how it can solve the problem
but if you have some good idea that requires a nonintrusive patch on the scrapyd part
you can suggest it here.

**Comment by borisdev** [comment]
Maybe writing a python client wrapper can handle the new complexity you need. You could use the python scrapyd api: http://python-scrapyd-api.readthedocs.org/en/latest/.
