### ISSUE TITLE
How to make scarpyd as a sevice with systemd?

### ISSUE THREAD

**Issue by hsnusonic** [scrapy/scrapyd#217]
I use miniconda3 to create a environment "scrapy" for my scrapy application. Then, I create a scrapyd.service unit file like below.
```
[Unit]
Description=scrapyd
After=network.target

[Service]
User=root
Environment="PATH=/path/to/miniconda3/envs/scrapy/bin:$PATH"
ExecStart=/bin/bash -c 'source /path/to/miniconda3/bin/activate scrapy; /path/to/miniconda3/envs/scrapy/bin/scrapyd --rundir=/my/scrapyd'

[Install]
WantedBy=multi-user.target
``` 

The web page can show after the service started. However, the spider cannot executed correctly and there are no logs produced. Everything will be OK if I manually start scrapyd in command line.
Can anyone give me some directions?

My environments:
python (3.5.2)
Scrapy (1.1.1)
scrapyd (1.2.0a1)
twisted (17.1.0)

**Comment by Digenis** [comment]
I see that you are using twisted 17
Maybe https://github.com/scrapy/scrapy/pull/2558
or https://github.com/scrapy/scrapy/issues/2479
can be the reason.

Try an older version of twisted (at least <17) and tell us if it solves the problem.
If it still doesn't work, read bellow.

What we need to investigate the issue is the missing log file.
We'll also need to figure out why the log is missing.

Try the following:

I suspect that you see no log because of journald (part of systemd).
You'll may need to use journalctl to display scrapyd's logs.

Try the `-l` argument to specify a log file in /tmp/ instead of stdout.

Because of #70, `--rundir` may not work as expected.
Can you try `cd /path/to/rundir/ && /path/to/miniconda3/envs/scrapy/bin/scrapyd` instead?

**Comment by podolskyi** [comment]
@hsnusonic 
I think you need set `WorkingDirectory`  

example my working configuration 

```
Unit]
Description=Scrapyd service
After=network.target

[Service]
User=crawler
Group=crawler
WorkingDirectory=/home/crawler/crawler/src
Environment="PATH=/home/crawler/crawler/venv/bin"
ExecStart=/home/crawler/crawler/venv/bin/scrapyd
Restart=always

[Install]
WantedBy=multi-user.target

```

**Comment by hsnusonic** [comment]
Thanks a lot @Digenis & @podolskyi

I try `cd /path/to/rundir/` and scrapyd can find projects correctly.
Also, I use `-l` argument to see logs, so I can find what the problem is.
I forgot to add PATH for "PhantomJS" executable... because I use it in my crawler.

**Comment by Digenis** [comment]
@hsnusonic, nice to see that you solved it.

@hsnusonic, @podolskyi,
This is a chance to improve scrapyd.
Do you want to open a PR to include a complete systemd init script for scrapyd?

**Comment by tumregels** [comment]
This is somewhat modified version of `scrapyd.service`
This way the spider can call other programs because it can see the paths.

```
[Unit]
Description=Scrapyd service
After=network.target

[Service]
User=scrapy
Group=scrapy
WorkingDirectory=/opt/scrapyd
ExecStart=/bin/bash -c 'PATH=$PATH /opt/scrapyd/env/bin/scrapyd'
Restart=always

[Install]
WantedBy=multi-user.target
```
