### ISSUE TITLE
POST several jobs at once on Scrapyd server

### ISSUE THREAD

**Issue by bezkos** [scrapy/scrapyd#236]
I have a Scrapyd instance and i post new jobs from time to time based on some criteria. 
I found out that need around 1 second to POST each job (limitation?).
I think it ll be great addition to have a way to POST several job at once so we can avoid this 1 second per job limitation.

Nvm about 1sec per POST. I found its limitation on my development server (dont know why), in production i can see multiple POSTs in same time.
Ofc my main question is if we can do one POST with multiple jobs instead of hunders POSTs with 1 job each time.

**Comment by Digenis** [comment]
Are you sure that you are timing post requests and not job starts per second?
In the second case, you may need to tweak the `poll_interval` setting.

Do you want the webservice to accept multiple jobs for convenience reasons
or do you have performance issues?
If the issue is performance, how do you expect such a change to improve it?
Have you pinpointed the bottleneck?
There are considerations if we change the webservice to schedule multiple jobs.
The post body format will probably become more complicated.
The server's response will also need to be encapsulated in an array
for each successful/failed schedule.

**Comment by bezkos** [comment]
In development server, i see 1 sec per POST in logs and yes i use in develop/production same poll_interval=0.1 on both servers. In production i see in logs multiple POSTs in same time.
So i guess somehow its a limitation in development server and keep in mind i use patched version of Scrapyd with PostGre.
I guess if we have a new feature with multiple jobs per POST, we ll achieve both gain in convenience and performance.
Is it better instead of see in logs hundeds POSTs to see only one each time?
Atm i dont have any visible kind of bottleneck but i guess to fill PostGre Scrapyd queue with one record each time can make troubles if someone has bigger implementation than me.

**Comment by jpmckinney** [comment]
This feature request has not received additional interest. Since there is no performance bottleneck, this seems like a "nice-to-have".
