### ISSUE TITLE
Prevent eggs_dir, dbs_dir, items_dir, logs_dir from using same directory, at startup

### ISSUE THREAD

**Issue by ghost** [scrapy/scrapyd#237]
I installed scrapyd 1.2.0 with python 3.5 on ubuntu xenial. When I start the service, it creates a twisted.pid file in it's working directory. When I consequently deploy a project, it creates several db files with one or more '.db' extensions. It creates 14 projectname.db, projectname.db.db etc. files, but also 14 twistd.pid.db, twistd.pid.db.db etc. files. When I redeploy a version of the project, again more of these db files are created. When the deamon is restarted, again more db files are created and the deamon forgets the job history.

A renewed setup of the install didn't remove the issue.

**Comment by Digenis** [comment]
@przewalski, what is your scrapyd configuration?
By default¸the databases should be under a `dbs/` directory
as configured by the default `dbs_dir` option.
Also, the job history is not kept by scrapyd, only the pending queue is.

**Comment by przewalski** [comment]
I've solved the issue, it might be useful to others.
I did set the various file locations in the config to the same directory like so:
```
eggs_dir=/var/lib/scrapyd/
dbs_dir=/var/lib/scrapyd/
items_dir=/var/lib/scrapyd/
```
I didn't mind them sharing the same directory.

When I changed the setup to separate subdirectories like so:
```
eggs_dir=/var/lib/scrapyd/eggs
dbs_dir=/var/lib/scrapyd/dbs
items_dir=/var/lib/scrapyd/items
logs_dir=/var/log/scrapyd
```
the issue vanished.

It seems scrapyd can't handle the db's, items and eggs sharing the same directory.

**Comment by Digenis** [comment]
> It seems scrapyd can't handle the db's, items and eggs sharing the same directory.

though it should (theoretically) since they use distinguishable filename extensions.

It can be fixed. I think items will need a separate directory
because different exporters may use arbitrary extensions
but this can be checked at start up, when reading the config.

@przewalski, thanks for reporting this issue and helping improve scrapyd.
If you feel like it, you can try patching it and opening a pull request here, in github.

**Comment by Digenis** [comment]
Postponed for when we drop py2 support.
#338 is relevant because as a side effect it fixes one case of this bug.
However it's not a fix, since a real fix would be checks on application loading
that don't allow such misconfiguration.

**Comment by jpmckinney** [comment]
Yes, issue is that Scrapyd assumes anything in eggs_dir is an egg (project), and it creates a corresponding database for each project.

Scrapyd also deletes items and logs according to `jobs_to_keep`, and setting all these directories to the same directory will cause the wrong files to be deleted.

**Comment by jpmckinney** [comment]
Actually, it's not clear where to implement this, since `eggs_dir` is only known to one particular implementation of the eggstorage interface. That said, since `eggs_dir` is the most problematic one, and since it gets checked at startup (via QueuePoller.__init__ -> update_projects -> get_spider_queues -> get_project_list -> list_projects), we could compare it to the other directories. However, this kind of breaks encapsulation.

**Comment by jpmckinney** [comment]
I added admonitions in the docs. This has only been reported by one user, who since then deleted their GitHub account. I don't anticipate this is a common issue. It is unusual to change all `*_dir` settings to use one directory.

I'll close and leave it as documentation, but can re-open if others misconfigure this similarly.
