### ISSUE TITLE
scrapy Failed to establish a new connection: [Errno 111] Connection refused',))

### ISSUE THREAD

**Issue by guangbaowan** [scrapy/scrapyd#263]
Hi, We are deploying the scrapy on docker (scrapyd (1.1.0), scrapyd-client (1.0.1))
we restart(cronjob) the job by send message to 'http://0.0.0.0:6800/cancel.json' and got
```
Traceback (most recent call last):
File "stop_spiders.py", line 31, in 
main()
File "stop_spiders.py", line 8, in main
jobs = requests.get(job_url)
File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 67, in get
return request('get', url, params=params, **kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=6800): Max retries exceeded with url: /listjobs.json?project=chaos (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa3b8b71b10>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by Digenis** [comment]
You are not using a correct ip address

**Comment by guangbaowan** [comment]
@Digenis , No, I'm running this on a docker, not every time the job cant post to scrapyd, most of the times it worked.

**Comment by sieira** [comment]
I'm experiencing the same issue, scrapyd is accessible from within the container, but not from the outside.

my bind_address is 0.0.0.0

**Comment by guangbaowan** [comment]
@sieira  I'm running the job in the docker

**Comment by Digenis** [comment]
@sieira, you can't connect to 0.0.0.0, it's not a real ip.
Let me make it simple:
When software listens for connection on 0.0.0.0,
it means it accepts connections from any ip.
On docker, you probably have to do extra work
to expose the port (6800) out of the container.
Are you using scrapyd-client when the error occurs?
If so, how? Try using a real ip, probably 127.0.0.1 will do for you.

**Comment by Alaminpramanik** [comment]
scrapyd_1        | 2021-06-28T08:40:49+0000 [twisted.python.log#info] "172.21.0.1" - - [28/Jun/2021:08:40:48 +0000] "GET / HTTP/1.1" 200 706 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
upstal_web       | query string with try  plumber usa facebook
upstal_web       | scrapy exception HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /schedule.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb8c953c70>: Failed to establish a new connection: [Errno 111] Connection refused'))

when i search my data then show this error please help me and how to solve my error. Thank you

**Comment by jpmckinney** [comment]
No Docker or Docker Compose files where shared here, so it is not possible to debug. You can compare your files to those shared in https://github.com/scrapy/scrapyd/issues/405
