### ISSUE TITLE
Scrapyd NOT Enable Item Pipelines

### ISSUE THREAD

**Issue by StevePhan97** [scrapy/scrapyd#271]
Hello, I'm having problem using Scrapyd service. I use MongoDB Pipeline to write scraped items to database. It works fine when I directly run spider on command line : 
`scrapy crawl digi`
`2018-01-22 13:25:18 [scrapy.middleware] INFO: Enabled item pipelines:
['tutorial.pipelines.MongoPipeline']`
When I send curl request to scrapyd server, the spider still runs. However, the item pipelines are not enabled:
`2018-01-22 13:29:32 [scrapy.middleware] INFO: Enabled item pipelines:
[]`
Could you suggest any solutions for this?

**Comment by Digenis** [comment]
There was an issue with some components
figuring out that they are not in a project (without a data directory)
and raising a NotConfigured exception, telling scrapy not to load them.
The http cache midleware was such.
There were discussions about this and maybe they changed it in recent releases.
Since you are doing the tutorial, read  pipeline's code and see if this is the case,
does it try to get to the project's data directory somehow?

**Comment by StevePhan97** [comment]
Hello, sorry for bothering you. It's actually simple error. I didn't re-setup egg file after modifying some of my spiders scripts. So the scrapyd server did not use the most recent update in data directory. Problem solved. Thanks a lot

**Comment by Digenis** [comment]
ok, I'm closing this.
feel free to reopen it if the problem persists.

**Comment by jpmckinney** [comment]
1. Make sure the item pipeline is activated as described here: https://docs.scrapy.org/en/latest/topics/item-pipeline.html#activating-an-item-pipeline-component

2. Make sure the file containing that setting is discoverable using entry_points like at https://github.com/scrapy/scrapyd-client#including-static-files
