### ISSUE TITLE
cancel.json terminates running jobs of all projects

### ISSUE THREAD

**Issue by my8100** [scrapy/scrapyd#345]
Both running jobs ('project1', 'jobid') and  ('project2', 'jobid')
would be terminated when cancelling ('project1', 'jobid').

**Comment by Digenis** [comment]
I think you meant to say: 
"terminates running jobs by jobid, regardless of the project"

This was rarely an issue with the default jobid scheme
but we should make the scope of the jobid clear in the doc.

Users reading the old doc should have assumed
that the jobid scope is project-wide
since cancel.json and other services for querying a job
require a project argument, as documented in api.rst.
Also, cancelling pending jobs already works this way,
the cancelling of running jobs is what's inconsistent.

So, because it's implied in the docs
and it's inconsistent with other services,
there's no question, it's a bug.
Also, anyone doing something useful with it
almost certainly has noticed the bug
and should have given us a notice,
so the fix is backwards-compatible.

**Comment by my8100** [comment]
Yes, that's what I want to express.
For me, it's an obvious bug from the perspective of source code and the current API.
