### ISSUE TITLE
Process died: exitstatus=None

### ISSUE THREAD

**Issue by gangal86** [scrapy/scrapyd#372]
I started my Scrapy Crawler by Scrapyd, but it exited with the log such as

`[-] Process died: exitstatus=None  project='my_proj' spider='my_proj_spider' job='2020-04-08T13_52_53' pid=17035 log='logs/my_proj/my_proj_spider/2020-04-08T13_52_53.log' items='file:///root/work_dir/scrapyd/items/my_proj/my_proj_spider/2020-04-08T13_52_53.jl'`

Spider process exit after several hours rather than exiting immediately. And there are no coding errors in scrapy spider log.

**Comment by LI-BT2034** [comment]
I also encountered this problem. How did you solve it?

**Comment by gangal86** [comment]
Unfortunately, I was unable to solve this problem. I just run Scrapy without Scrapyd

**Comment by nvo87** [comment]
I have this problem too. Has anybody solved it?

**Comment by jpmckinney** [comment]
Can any additional information be provided? This is not possible to debug otherwise.

**Comment by jpmckinney** [comment]
Closing as no response to question in several months.

**Comment by jpmckinney** [comment]
So Scrapyd uses Twisted's [ProcessProtocol](https://docs.twisted.org/en/stable/core/howto/process.html#things-that-can-happen-to-your-processprotocol) to manage its subprocesses.

At some point, this ProcessProtocol's processEnded method is called. Per that documentation:

> This is called when all the file descriptors associated with the child process have been closed and the process has been reaped. This means it is the last callback which will be made onto a ProcessProtocol .

> The status is passed in the form of a [Failure](https://docs.twisted.org/en/stable/api/twisted.python.failure.Failure.html) instance, created with a .value that either holds a [ProcessDone](https://docs.twisted.org/en/stable/api/twisted.internet.error.ProcessDone.html) object if the process terminated normally (it died of natural causes instead of receiving a signal, and if the exit code was 0), or a [ProcessTerminated](https://docs.twisted.org/en/stable/api/twisted.internet.error.ProcessTerminated.html) object (with an .exitCode attribute) if something went wrong.

In Scrapyd's processEnded method, it just logs information and runs a callback (which adds the process to the list of finished jobs, and allows a new subprocess to start).

https://github.com/scrapy/scrapyd/blob/d3c43b08701b6f2a198a15a3b7fd7644884a4e36/scrapyd/launcher.py#L132-L137

So, having an `exitCode` of `None` like in this issue is very weird.

Your first log is truncated – the full message logged by processEnded is cut off.

The second one shows that the process run was:

`/usr/local/bin/python -m scrapyd.runner crawl wb_mason -a _job=ff9296c04f6211ef87de0242ac110004 -s LOG_FILE=/var/lib/scrapyd/logs/{my_project}/wb_mason/ff9296c04f6211ef87de0242ac110004.log'`

You can just run that command in the same environment and see what happens. By same environment, I meant the same directory and the same environment variables. You might need to set the environment variables `SCRAPY_PROJECT` to your Scrapy project's name, and `SCRAPYD_EGG_VERSION` to the version of the egg.

**Comment by jpmckinney** [comment]
But, yeah, in short, something is killing the process. Scrapyd does not kill processes (unless you explicitly cancel them using the cancel.json endpoint). It's either running out of resources, or hitting a bug somewhere else – or something else is killing the process. The `scrapyd.runner` module that is run by the subprocess is very simple. It basically just runs `scrapy crawl`: https://github.com/scrapy/scrapyd/blob/master/scrapyd/runner.py

My only guess is that maybe the `ulimit`s for a subprocess are different from your regular user. That's the only thing I can think of to explain earlier comments about the crawl working with Scrapy but not Scrapyd. A relevant ulimit might be the maximum number of open file descriptors. If your code (or code you depend on) opens lots of files without closing them, then maybe you hit that limit and the process fails.

----

I see "Error: write EPIPE" in your log, which can happen if a program to which data is piped doesn't read all the data, so it sends the EPIPE signal, and if your code doesn't handle that signal, then you see that error. Scrapyd doesn't use pipes for subprocesses (it uses them to essentially run `scrapy list` somewhere else). So, that part is surely your code.
