### ISSUE TITLE
Broken link in docs for installing on Ubuntu

### ISSUE THREAD

**Issue by joeharrison714** [scrapy/scrapyd#388]
I am attempting to follow the steps in the docs at https://scrapyd.readthedocs.io/en/stable/install.html#installing-scrapyd-in-ubuntu to install scrapyd in Ubuntu. However, the link in "They are shipped in the same APT repos of Scrapy, which can be added as described in Scrapy Ubuntu packages." is broken, and I could not find reference to the APT repos anywhere else.

**Comment by Digenis** [comment]
https://github.com/scrapy/scrapy/pull/3684

Yes, the official repo probably caught up with recent scrapy versions
but scrapyd is not distributed as a debian package.

We need to update this page, probably in a 1.2 post-release too,
but there's nothing to replacing it with.

E.g.:
You need to create a system user in /var/lib/scrapyd,
write a systemd service, copy the config in /etc
and install scrapyd and its requirements (as deb requirements).

The debian/ directory still exists in this repo
so that anyone up to the task can update it.
Then users will be able to at least build their own deb package.

**Comment by Digenis** [comment]
I forgot, it's already resolved in #252.
We just never made a post release for 1.2 (stable).

I'll cherry-pick 60039c76270c7020062bd41919fe0631846db1ca in branch 1.2
and release it as 1.2.1-post.1 to show the right documentation on readthedocs

**Comment by Digenis** [comment]
For the second issue, about installation documentation, there's already #258

**Comment by Digenis** [comment]
Actually, it would have been worth the trouble
if we had rolled out a post-release back when the apt repo existed
and users installing the outdated version from it
were opening issues about fixed bugs.

1.3 is getting in alpha stage, I think we can soon forget about 1.2
