### ISSUE TITLE
how can I get my custom attrs of a scrapy spider?

### ISSUE THREAD

**Issue by wtgg** [scrapy/scrapyd#390]
after I upload an egg file to scrapyd server and request for scrapyd's listspiders API, it returns me the names of spiders in the egg file. But how can I get other attrs of the spiders? like `allowed_domains`,  `start_urls`  and my custom attrs. It's important and emergent for me. Waiting online...

**Comment by brunobg** [comment]
Ran into myself. For other adventurers facing this: there's apparently no way to do that currently in scrapyd other than forking and adding a new rest endpoint.
If you can run scrapy directly, you can implement a [custom command](https://docs.scrapy.org/en/latest/topics/commands.html#custom-project-commands).

**Comment by Digenis** [comment]
Loading spiders to query their names or other attributes is an expensive operation
that's why their names are cached.
You'd need a custom webservice for this.

We can't predict what spider attributes can be important to users
and the possibilities are endless.

If you come up with some generic webservice for inspecting project eggs
I'd consider including it.
