### ISSUE TITLE
Add deljob.json endpoint to delete a job from finished jobs

### ISSUE THREAD

**Issue by agauravdev** [scrapy/scrapyd#423]
I am maintaining a different table with all the finished tasks in my Django project, so I would like to delete the tables in the scrapyd finished jobs list. Then I can move a task to my table and delete it from here. Is there a simpler solution to this? If not, then I have added this functionality and will put a pr soon.

**Comment by mxdev88** [comment]
Not 100% sure to understand your use case. Take a look at [finished to keep](https://github.com/scrapy/scrapyd/blob/master/docs/config.rst#finished_to_keep) and [jobstorage](https://github.com/scrapy/scrapyd/blob/master/docs/config.rst#jobstorage) which you could try by using the master branch.

**Comment by agauravdev** [comment]
I have built a small internal tool in my company to track scraping tasks that ran on the server. But some tasks fail and we do not want to keep those tasks in the list of the finished tasks. So, I have written an API (with the web interface too) to delete a task from the finished list using the task id. Hope it's more clear now.

**Comment by mxdev88** [comment]
I suppose an API endpoint `deljob.json` could be added similar to [delversion](https://github.com/scrapy/scrapyd/blob/master/docs/api.rst#delversionjson) for this purpose.

Personally, I think it could be useful. I would let the project maintainers comment on the idea. Feel free to submit a PR.

**Comment by jpmckinney** [comment]
This seems reasonable!

**Comment by agauravdev** [comment]
Coooll.. Will try to submit the PR this weekend. :D

**Comment by javiersrf** [comment]
Someone created the Pr?

**Comment by mxdev88** [comment]
I wonder how this feature would be expected to behave if one calls it for pending or running jobs. Shall we consider that one calling `deljob` would behave as a `cancel` for pending and running jobs? or fail with some error message? 
It seems there would be some sort of overlap in the two features. Maybe the `deljob` would supersede `cancel` and `cancel`would eventually be deprecated. Any thoughts?

**Comment by jpmckinney** [comment]
What state does a canceled job end up in?

I think there’s a semantic difference between canceling a running job and deleting a finished job. Only one of the two involves interrupting a process. (Similar to stopping vs removing a container.)

I would keep the APIs separate.

**Comment by agauravdev** [comment]
Oh I totally forgot about this PR. 🙇🏻‍♂️
I will try to finish it. I had written the code, but changed my laptop so mostly will write it again. 

But I agree with @jpmckinney that it should be kept separate. Trying to delete a running process should return an error to cancel the process or let it finish. Thanks for making this issue active again 🙇🏻‍♂️

**Comment by mxdev88** [comment]
> What state does a canceled job end up in?

Looking at the code it gets removed from the queue if pending or killed if running so no state; the job disappears.
 
> I think there’s a semantic difference between canceling a running job and deleting a finished job. Only one of the two involves interrupting a process. (Similar to stopping vs removing a container.)

Yep, fully agree on the semantic difference. I was just wondering because in the end the cancel removes the job as if it never existed, which is sort of a deletion.
 
> I would keep the APIs separate.

ok :)

**Comment by jpmckinney** [comment]
Aha - presently the state change is the same, but I can imagine in the future that cancelling a running job puts it in the end-state "cancelled" rather than deleting it. (If we were to implement this in the future, then deljob could delete either cancelled or finished jobs.)

**Comment by mxdev88** [comment]
Makes sense!

**Comment by jpmckinney** [comment]
The `IJobStorage` interface only has add, list, len, iter methods, and implementations of the interface use the `finished_to_keep` config to clear out old jobs in their `add` method.

So, you could create a custom job storage with a delete method and create a [custom webservice](https://scrapyd.readthedocs.io/en/latest/config.html#services-section) to delete finished jobs. (Or, you could have the new webservice dig into the existing job storage's implementation, to edit the job backend directly – but this is not future-proof, since those internals are not guaranteed to be stable.)

I'm not very clear on the use cases. It seems like the motivation is just tidiness – but there's not really any downside to keeping some jobs in finished jobs (like a few kilobytes of memory for MemoryJobStorage or of disk space for SQLiteJobStorage).

Making this generic would require updating the interface, and we don't know what alternative interfaces exist in the wild – so it would be a somewhat breaking change (e.g. user with custom job storage upgrades Scrapyd, Scrapyd now has a deljob.json webservice, but it causes errors when users of that deployment call it, because the job storage doesn't have a delete method).

Since this seems like a fairly narrow need, I'll close for now, but can reopen if there is demand (and better clarity on what's the problem with leaving jobs in the finished list).
